### ISSUE TITLE
just saying I love the project

### ISSUE THREAD

**Issue by r3k2** [manicatorman/thebreadbook.org#2]
In any way our collective can help let us know.. server/donations etc whatever..
https://hispagatos.org
we also have a anarcho hacker show in Spanish we can mention your project for the latin/hispanic comrades. <3
maybe we can even get someone to help translate to Spanish

**Comment by manicatorman** [comment]
@ChrisFernandez, would you like to help translate the site into Spanish? I already have somebody who has translated it into Polish, but I thought we might want to get a language that is more widely spoken before we add multiple languages in general. Do you think you would be up for it, or do you know somebody who would be? You obviously wouldn't have to translate the actual Bread Book again, since I believe a Spanish translation is available; all we would need is the introduction, maybe a couple of posters/stickers in Spanish, and then some good Spanish-language community resources.

**Comment by r3k2** [comment]
@manicatorman I may be able to get someone from our collective to do it, at the moment busy this next two weeks because of conferences and such but I will get back to you soon

**Comment by dkreimer** [comment]
Hey just stumbled into this after checking out your site - would be happy to translate the site into Spanish and/or French (fluent in both). Finding community resources in Spanish/French sounds like a bigger task but I can easily get your front page and stickers done in a few days. Let me know if that's useful!

**Comment by manicatorman** [comment]
@dkreimer Yes, that would be awesome! For community resources - I'm working on trying to get it to be more international. But don't worry about that for now, I'll work on that. You are awesome!

**Comment by dkreimer** [comment]
@manicatorman I have the intro page in Spanish and I've sent it to a few people to beta read for neutrality and other stuff I might have overlooked. In the meantime, what's a good way for me to translate the stickers? 
I'm guessing you have whatever project files you used to make them in the first place, so would a .txt file with just the translation of each slogan be fine?

**Comment by manicatorman** [comment]
@dkreimer Yeah, a txt file would be perfect

**Comment by germinolegrand** [comment]
Hi, came across your site today, found the idea and the slogans awesome ! So I did a FR translation : https://github.com/manicatorman/thebreadbook.org/pull/10

You can see the result here : https://germinolegrand.github.io/thebreadbook.org/index.html
